---

env:
  global:
    - CC_TEST_REPORTER_ID=${{ test_reporter_id }}

language: node_js
node_js:
  - node

before_script:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test-coverage
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: falset
